apiVersion: apps/v1
kind: Deployment
metadata:
  name: "networktools"
  namespace: nwtools
spec:
  selector:
    matchLabels:
      app: "networktools-label"
  replicas: 1
  template:
    metadata:
      labels:
        app: "networktools-label"
    spec:
      containers:
        - name: networktools
          image: nishantapatil3/networktools:latest
          command: ["/bin/sh"]
          args: ["-c","/bin/sh /entrypoint.sh;while true; do echo hello; sleep 100;done"]
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
